require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c",
		"css",
		"go",
		"graphql",
		"help",
		"javascript",
		"json",
		"json5",
		"lua",
		"markdown",
		"php",
		"ruby",
		"rust",
		"scss",
		"sql",
		"svelte",
		"tsx",
		"typescript",
		"vim",
		"vue",
		"yaml",
	},
	highlight = {
		enable = true,
		disable = { "NvimTree" },
		additional_vim_regex_highlighting = true,
	},
	textobjects = {
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				["if"] = "@function.inner",
				["af"] = "@function.outer",
				["ic"] = "@class.inner",
				["ac"] = "@class.outer",
				["ia"] = "@parameter.inner",
				["aa"] = "@parameter.outer",
			},
		},
	},
	context_commentstring = {
		enable = true,
	},
})
