#!/usr/bin/env bash

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install and setup NVM
NODE_VERSION=18.14.2
brew install nvm
source $HOME/.zshrc
mkdir ~/.nvm
nvm install $NODE_VERSION
nvm use $NODE_VERSION
nvm alias default $NODE_VERSION

# Install Neovim
brew install neovim

# Install Tmux
brew install tmux

# Install everything I need for Neovim
brew install wget
brew install lua-language-server
brew install fzf
brew install proselint
brew install gitlint
brew install luacheck
brew install php-cs-fixer
brew install jq
brew install stylua
brew install ripgrep
brew install fd
brew install luarocks
