#!/usr/bin/env bash

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install and setup NVM
brew install nvm
source $HOME/.zshrc
mkdir ~/.nvm
nvm install --lts --default
nvm use --lts

# Install Neovim
brew install neovim

# Install Tmux
brew install tmux

# Install everything I need for Neovim
brew install wget
brew install lua-language-server
brew install fzf
brew install proselint
brew install gitlint
brew install luacheck
brew install php-cs-fixer
brew install jq
brew install stylua
brew install ripgrep
brew install fd
brew install luarocks

# Node dependent packages independently from NVM in order to use the most up to date versions
brew tap oven-sh/bun
brew install bun
brew install yarn
brew install pnpm

# Install Languages
brew install php
brew install elixir
brew install rust
# todo look up how to install this vs chruby
# brew install rbenv
# rbenv install -l
# brew install go # decide if I want to use brew or my custom go installer script

# Random
brew install telnet
brew install protobuf
