#!/usr/bin/env bash

#npm i -g yarn
#npm i -g pnpm
npm i -g prettier vls @tailwindcss/language-server emmet-ls typescript typescript-language-server bash-language-server
npm i -g solhint
npm i -g rustywind
