# Enable History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

source $HOME/bin/sources

path=(
	$HOME/.flutter/bin
	$HOME/.local/bin
	$HOME/bin
	$path
)

export PATH


# ------- NVM
export NVM_DIR="$HOME/.nvm"
  [ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh"  # This loads nvm
  [ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && . "$(brew --prefix nvm)/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
